version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - IMAGE_TAG=test
      - branch=`echo $CODEBUILD_INITIATOR | awk -F'-' '{ print $NF }'`
      - if [ -n "$branch" ]; then IMAGE_TAG=$branch; fi
      - ls -lR
      - lasttime=$(aws ecr describe-images --region $AWS_DEFAULT_REGION --repository-name $IMAGE_REPO_NAME --image-ids imageTag=$IMAGE_TAG | jq -r '.imageDetails[0].imagePushedAt')
      - dockerchange=$(find src/docker -newermt '@'$lasttime | wc -l)
      - echo lasttime $lasttime $dockerchange
      - if [ "$dockerchange" ]; then echo Building the Docker image... $dockerchange ; fi
      - docker build -t $IMAGE_REPO_NAME:main.base src/docker
      - docker tag $IMAGE_REPO_NAME:main.base    $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - cd $CODEBUILD_SRC_DIR/lambda_services; zip -r /tmp/job.zip job_service
      - cd $CODEBUILD_SRC_DIR/lambda_services; zip -r /tmp/id.zip api_service
      - aws lambda update-function-code --function-name apbs-$IMAGE_TAG-job-L --publish --zip-file fileb:///tmp/job.zip
      - aws lambda update-function-code --function-name apbs-$IMAGE_TAG-id-L  --publish --zip-file fileb:///tmp/id.zip
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
