# configure ops
- name: query aws hosts
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Query EC2 instances
      ec2_instance_facts:
        profile: "{{ aws_profile }}"
        region: "{{ aws_region }}"
        filters:
          "tag:Name": "{{ project }}-{{ deployment_group }}-archive"
      register: ec2

    - name: add server ip addresses to hosts group
      add_host:
        hostname: "{{ item.public_ip_address }}"
        groupname: ops
      with_items: "{{ ec2.instances }}"
      tags: ec2

    - name: Debug launched group
      debug: var=groups['ops']

- name: ec2 ops
  hosts: ops
  remote_user: ec2-user
  become: true
  become_method: sudo
  gather_facts: True
  roles:
    - role: yum-cron
    - role: sendmail
    - role: nessusagent
    - role: upload
    - role: ops
    - role: codedeploy
