- name: Copy rpm file to server
  copy:
     src: files/{{ nessus_agent_package }}
     dest: /tmp/{{ nessus_agent_package }}
  tags: nessus

- name: Install nessusagent
  yum:
     name: /tmp/{{ nessus_agent_package }}
     state: present
  tags: nessus

- name: Check agent link status
  command: /opt/nessus_agent/sbin/nessuscli agent status
  become: yes
  register: nessus_link
  ignore_errors: yes
  changed_when: nessus_link.rc != 0

- name: Configure Nessus Agent
  command: >
      /opt/nessus_agent/sbin/nessuscli agent link
      --key={{nessus_agent_key}}
      --host={{nessus_agent_host}}
      --port={{nessus_agent_port}}
      --groups="{{nessus_agent_group}}"
  become: yes
  when: nessus_link is failed
  notify:
   - restart nessusagent
  tags: nessus

- name: Ensure nessusagent is started
  service:
    name: nessusagent
    state: started
    enabled: yes
  tags: nessus
